### ISSUE TITLE
Automatic Report Generation from CKAN Contents

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-management-plan#1]
[Export datasets from CKAN on the command line ](https://metaodi.ch/posts/2019/02/export-ckan-datasets/) with [ckanapi](https://github.com/ckan/ckanapi) and use [carbone.io](https://carbone.io/) to generate documents out of Data Package JSON.

Example: Dump Resource [Summer days (SD)](https://ckan.myclimateservice.eu/dataset/summer-days-sd) as **Data Package**:

```sh
ckanapi dump datasets "summer-days-sd" -r https://ckan.myclimateservice.eu/ \
--datapackages=./dump_directory/
```

See also https://github.com/clarity-h2020/ckan/issues/16

#### Related Tasks:
- [x] [Create Dataset Template](https://github.com/clarity-h2020/data-management-plan/issues/3)
- [x] [Create ckanapi export statements](https://github.com/clarity-h2020/data-management-plan/issues/4)
- [x] [Support For Markdown](https://github.com/clarity-h2020/data-management-plan/issues/2)

**Comment by p-a-s-c-a-l** [comment]
> Hello “{d.firstname} {d.lastname}”!

![grafik](https://user-images.githubusercontent.com/1788226/77619253-205c6800-6f38-11ea-8cf1-e712017a6903.png)

**Comment by p-a-s-c-a-l** [comment]
> Hello {d.firstname} {d.lastname} !

![grafik](https://user-images.githubusercontent.com/1788226/77619522-a9739f00-6f38-11ea-83d7-c0a1f533967f.png)

**Comment by p-a-s-c-a-l** [comment]
Hm, https://github.com/clarity-h2020/data-management-plan/issues/1#issuecomment-604264810 probably caused by bookmark xml tags. 🙄 


![grafik](https://user-images.githubusercontent.com/1788226/77620008-bc3aa380-6f39-11ea-88e0-9c5b96ca1ee3.png)

![grafik](https://user-images.githubusercontent.com/1788226/77620116-f146f600-6f39-11ea-9bd1-102e86771506.png)

**Comment by p-a-s-c-a-l** [comment]
> {d.firstname}

```xml
<w:r w:rsidRPr="002E7781">
	<w:rPr>
		<w:rFonts w:asciiTheme="minorHAnsi" w:hAnsiTheme="minorHAnsi"/>
		<w:sz w:val="22"/>
	</w:rPr>
	<w:t>d.firstname</w:t>
</w:r>
```

-> carbone

![grafik](https://user-images.githubusercontent.com/1788226/77620898-a75f0f80-6f3b-11ea-96ca-679fb5662100.png)

:hurtrealbad:

**Comment by p-a-s-c-a-l** [comment]
ckanapi [Action Arguments](https://github.com/ckan/ckanapi#action-arguments):

Very ambiguous. What's the role of the JSON Here? The result of the API call? But why the parameter `id` in the API result and the parameter `name`in the JSON result?  

This does not work:

`ckanapi action package_show id="Summer days (SD)" -r https://ckan.myclimateservice.eu/`

> raceback (most recent call last):
  File "B:\Python27\Scripts\ckanapi-script.py", line 11, in <module>
    load_entry_point('ckanapi==4.3', 'console_scripts', 'ckanapi')()
  File "b:\python27\lib\site-packages\ckanapi\cli\main.py", line 112, in main
    for r in action(ckan, arguments):
  File "b:\python27\lib\site-packages\ckanapi\cli\action.py", line 57, in action
    files=file_args)
  File "b:\python27\lib\site-packages\ckanapi\remoteckan.py", line 87, in call_action
    return reverse_apicontroller_action(url, status, response)
  File "b:\python27\lib\site-packages\ckanapi\common.py", line 126, in reverse_apicontroller_action
    raise NotFound(emessage)
ckanapi.errors.NotFound: Not found

**WHAT** not found? command? resource?

**Comment by p-a-s-c-a-l** [comment]
Example from  [Action Arguments](https://github.com/ckan/ckanapi#action-arguments) doesn't work either:

`ckanapi action package_search 'facet.field:["organization"]' rows:0 -r https://ckan.myclimateservice.eu/`

> KEY:JSON argument u"'facet.field" has invalid JSON value u"[organization]'"

😞

**Comment by p-a-s-c-a-l** [comment]
[Array Manipulation](https://carbone.io/documentation.html#formatters) does not work:

`{d.tags:arrayMap("; ",|,name)}`

> CLARITY&quot;;&quot;Climate Indicators&quot;;&quot;EURO-CORDEX&quot;;&quot;WP3&quot;;&quot;open-data&quot;;&quot;output-data

**Comment by p-a-s-c-a-l** [comment]
`{d.tags:arrayMap(;  ,|,name)}`
> CLARITY;Climate Indicators;EURO-CORDEX;WP3;open-data;output-data 

It seems that no quotes nor commas are supported in (ODT) templates. 😞

**Comment by p-a-s-c-a-l** [comment]
```json
"tags": [{
            "display_name": "CLARITY",
            "id": "fdb805ad-2f49-4cf5-b498-01a7d7afdd14",
            "name": "CLARITY",
            "state": "active",
            "vocabulary_id": null
        }, { ...
```

None of  these works:
```
{d.tags:arrayMap(“, “ ,| ,display_name)}
{d.tags:arrayMap(`, ` ,| ,display_name)}
{d.tags:arrayMap(", " ,| ,display_name)}
```

> “CLARITY““Climate Indicators““EURO-CORDEX““WP3““open-data““output-data
`CLARITY``Climate Indicators``EURO-CORDEX``WP3``open-data``output-data
&quot;CLARITY&quot;&quot;Climate Indicators&quot;&quot;EURO-CORDEX&quot;&quot;WP3&quot;&quot;open-data&quot;&quot;output-data

**Comment by p-a-s-c-a-l** [comment]
As workaround use `{d.tags:arrayMap(;,|,display_name)}`:
> CLARITY;Climate Indicators;EURO-CORDEX;WP3;open-data;output-data

**Comment by p-a-s-c-a-l** [comment]
It seems that there are more general problems with quotes and spaces: https://github.com/Ideolys/carbone/issues/59#issue-538315672

```
    • {d.test:ifEmpty(“some other sentence”)}
    • {d.test:ifEmpty(very strange)}
    • {d.test:ifEmpty(very, strange )}
    • {d.test:ifEmpty( very, strange )}
    • {d.test:ifEmpty(very; strange)}
    • {d.test:ifEmpty(\n  1    2   3)}
    • {d.test:ifEmpty(;       123 4)}
    • {d.test:ifEmpty(;   \n    123 4 X)}
```

![grafik](https://user-images.githubusercontent.com/1788226/77643006-e81c5000-6f5e-11ea-92f9-71669b264d3c.png)

**Comment by p-a-s-c-a-l** [comment]
ENV VAR substitution does not work: 
> CLARTIY H2020 Data Management Plan v${GITHUB_REF} generated by ${GITHUB_ACTOR} from CLARITY CKAN Build #${GITHUB_RUN_NUMBER} triggered by ${GITHUB_SHA}

That's the the typical variables mess in YAML: `${{ github.ref }}` vs `${GITHUB_REF} ` : [github-context](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) vs [env-context](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#env-context). WTF?

Now, how to get the output on an ENV var? 
- ${{ ENV_VAR }}
- ${ENV_VAR}
- $ENV_VAR
- ${{ env.VAR }}
- ???

**Comment by p-a-s-c-a-l** [comment]
According to [using environment variables](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables) we can use e.g. `$GITHUB_REF` . But in reality this leads to:

> Your workflow file was invalid: The workflow is not valid. .github/workflows/release.yml (Line: 71, Col: 15): Unrecognized named-value: 'GITHUB_REF'. Located at position 1 within expression: GITHUB_REF

**Comment by p-a-s-c-a-l** [comment]
done
